### PR TITLE
Open main window on chat

### PR DESCRIPTION
**Pull request by alescdb**
Add an option (false by default) to open chat window when a message is received.

### CODE REVIEW

**Comment by alescdb** [comment]
It seems that "unreadCount" is not always called (at least for me on linux) when a new message is received.

**Comment by ankurk91** [comment]
Did you test this feature in MacOS ? and in app states ?

**Comment by alescdb** [comment]
> Did you test this feature in MacOS ? and in app states ?

Nope, only on linux, I do not have access to a MacOS system, but MacOS should be able to show the window, no ?
If not, we can make a condition excluding mac.

**Comment by ankurk91** [comment]
I want it to work well on all platforms

**Comment by ankurk91** [comment]
You are doing too many things in a single PR

**Pull request closed without merging**
