### PR TITLE
Fix : This browser or app may not be secure

### PR DESCRIPTION
**Pull request by KorbsStudio**
macOS (Working):
image

Linux (Working):
image

Windows 7 (Working):
image

### CODE REVIEW

**Comment by KorbsStudio** [comment]
This should fix #52

**Comment by ankurk91** [comment]
We are already overriding user agent
https://github.com/ankurk91/google-chat-electron/blob/76318c710f4fb8bb17636877b03e83480306e291/src/main/features/userAgent.ts#L7

We are using Firefox user agent string here.

**Comment by ankurk91** [comment]
I have merged your commits locally, but with Firefox user agent.

But the issue still not fixed for me, i am still getting same error upon login.

**Comment by KorbsStudio** [comment]
Uh, the user agent I used works for me.
Confirmed on Windows 7, macOS, and Linux.

**Comment by ankurk91** [comment]
Follow these steps:

* Quit from app completely.
* Remove the cache folder of this app; for example on Linux
```
/home/ankur/.config/google-chat-electron
```
* Now launch the app, This should be first launch of the app.
* Enter your personal gmail address (not an organisation one)
* Notice you wont be able to login now.

Looks like google is also checking several other things not just User Agent. There is no easy way to spoof Google.

**Comment by KorbsStudio** [comment]
Ah I see the issue. I didn't full test.

**Pull request closed without merging**
